language: java
jdk:
- oraclejdk8
install:
- mvn clean package
deploy:
  provider: releases
  api_key:
    secure: Vh71kOArns8qUivGDEcr0IedeRsm2H4o4B8TckjOYP8vdBBSxkPiKATTFDBjYW14NbkuD3Lu7M4Wy0wOMwSaL67tz/Gdl7gBTlr4FZL9ESrPvrapQPXVwj35Jty1kxq5lJV34Mg1kgod93DOUySeFumhct0CGNFs9dATtEHcZD155NirU81Q39nCjGdf/8gyAVso6q/V8Y2w6gi1isikbcDMwmW/hi3AlizA+uOXK16ZRA9sfrY9dtHgGv0fx7empPTg4xgM1OnkstZL5je8iUvq7td7XxiO03nAIGJ6QdfhVLdk5PuFqmz7p+FWL4O8xdt8BD4xoO3VpSV2lwgz1miOMg6h3IArxAejADKWIj9ThPjO5gmnzAK3Ctedidumq2zA2mu889t5mhxNxSwneC/Ni4g+GGcpsK5Z6uX9cql9WP9QmPLSKPsu1xp/1Y1LjOBsHMvbc+/sxbBFf4M4LKNU1aqtTFArOWOxmdJCGVb7QEGyYttZ1+F9I9eO6Om+XAnuRDgPs2DqjisO6exoTLvrGo0Iy12XBRM5DvB45xVxzizNqCxt0SzXXLnDaVqrRCMlouyqfCdsams4PqqVZ5/uIt3329wKmPoU0zO3t9yfKlgmG+iAKSC6KLurjE/M+rk77tKYdlTZB4Q+9uPJzO4S7CHCv6KTc8ciDtVp28Q=
  file: "target/clickCount.war"
  on:
     branch: release
     tags: true
env: 
  - TRAVIS_TAG=v1.0
